#!/bin/bash

FILE="ftip.py"
DIR="$HOME/Personal_BH/Maintenance"
FIL="ftip"


#
#

cp $FILE   "$DIR/bin"
chmod 755  "$DIR/bin/$FILE"
cp "$FILE" "$DIR/bin/$FIL"
chmod 755  "$DIR/bin/$FIL"

cp "$FILE"    ~/bin
chmod 755     ~/bin/"$FILE"

cp ./"$FILE" "$HOME/bin/$FIL"
chmod  755   "$HOME/bin/$FIL"
